org: asimami
app: license-check-py
service: license-check-py

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8
  tags:
    name: license_check_py
    project: license_check

functions:
  cronHandler:
    handler: handler.run
    events:
      - schedule: cron(5 9-4 * 8-9 ? 2022)
